name: jupyter-earth

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - scipy
  - matplotlib
  - ipywidgets
  - pip
  - pip:
    - jupyterbook
    - sphinxcontrib-bibtex<2.0.0
